const q = (s) => document.querySelector(s);
const qa = (s) => [...document.querySelectorAll(s)];
let state, filter = 'all', toastTimer, importContent = '', importPreview = [], batchWrongNumbers = new Set();
const esc = (v = '') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const plan = () => state?.plans.find(x => x.id === state.active_plan_id) || state?.plans[0];
const book = (p = plan()) => p && state.wordbooks.find(x => x.id === p.wordbook_id);
const papers = (p = plan()) => p?.week.papers || [];
const words = (p = plan()) => { const b = book(p); const ids = p?.week.frozen_word_ids?.length ? p.week.frozen_word_ids : p?.week.word_ids || []; return ids.map(id => b?.words.find(w => w.id === id)).filter(Boolean); };

function notice(message) { const el=q('#toast'); el.querySelector('span').textContent=message; el.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.classList.remove('show'),3600); }
async function api(path, options={}) { const res=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options}); const data=await res.json().catch(()=>({})); if(!res.ok) throw new Error(data.error||'操作失败，请重试。'); return data; }
async function refresh() { state=await api('/api/state'); render(); }
function view(name) { qa('.view').forEach(x=>x.classList.toggle('active',x.id===name)); qa('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===name)); q('#crumb').textContent=({dashboard:'本周工作台',wordbooks:'我的词表',plans:'学习计划',documents:'文档中心'})[name]; window.location.hash=name; }

function render() {
  q('#book-total').textContent=state.wordbooks.length; q('#doc-total').textContent=state.documents.length;
  renderDashboard(); renderBooks(); renderPlans(); renderDocuments();
}
function renderDashboard() {
  const p=plan(), empty=q('#empty-dashboard'), content=q('#dashboard-content'); empty.classList.toggle('hidden',!!p); content.classList.toggle('hidden',!p); if(!p)return;
  const list=words(p); q('#week-stamp').innerHTML=`<b>${String(list.length).padStart(2,'0')}</b><small>本周已加入词条</small>`;
  q('#plan-name').textContent=p.name; q('#plan-summary').textContent=`第 ${p.week.number||1} 周期 · 每周期 ${p.weekly_target||list.length} 词 · ${list.length} 个本周期词条`;
  const loop=q('#exam-loop');if(loop)loop.innerHTML=[1,2].map(v=>{const item=papers(p).find(x=>x.version===v),done=!!item?.result_at,current=item&&!item.result_at;return `<span class="loop-dot ${done?'done':''} ${current?'current':''}"><i>${v}</i>${v===1?'周测':'复测'}</span>`}).join('');
  q('#week-words').innerHTML=list.slice(0,6).map((w,i)=>`<div class="word-row"><b>${String(i+1).padStart(2,'0')} · ${esc(w.word)}</b><span>${esc(w.meaning)}</span></div>`).join('')+(list.length>6?`<p class="word-more">另有 ${list.length-6} 个词条</p>`:'');
  renderPaper();
}
function renderPaper() {
  batchWrongNumbers = new Set();
  const panel=q('#current-paper'), p=plan(), all=papers(p), latest=all.at(-1); if(!p)return;
  if(!latest){ const previous=p.cycles?.at(-2); panel.innerHTML=`<p class="eyebrow">${p.status==='completed'?'PLAN COMPLETE':`CYCLE ${p.week.number||1}`}</p><h2>${p.status==='completed'?'全部周期已完成':'从周测开始'}</h2><div class="paper-callout"><strong>${p.status==='completed'?`最终周期评级：${p.week.grade||'—'}`:`本周期 ${words(p).length} 个词会随机编号。`}</strong><p>${p.status==='completed'?'本词表已按计划完成；各周期成绩可在“学习计划”中查看。':`${previous?.grade?`上一周期评级 ${previous.grade}；`:''}可直接在线答题，或生成带勾选卡的纸面周测。`}</p></div>${p.status==='completed'?'':`<div class="paper-buttons"><button class="primary-button" data-action="online-test" data-ver="1">在线周测</button><button class="secondary-button" data-action="exam-one"><svg aria-hidden="true"><use href="#i-printer"/></svg>下载周测</button></div>`}`; return; }
  const wrong=latest.wrong_numbers||[];
  if(latest.result_at){ const next=latest.version+1; if(next>2){panel.innerHTML=`<p class="eyebrow">CYCLE COMPLETE</p><h2>第 ${p.week.number||1} 周期已评级</h2><div class="paper-callout"><strong>${p.week.grade||'—'} · ${p.week.score||0} 分</strong><p>下一周期已自动准备，其中约 10% 为此前学过的词。</p></div><button class="primary-button" data-action="online-test" data-ver="1">开始下一周期周测</button>`;return;} panel.innerHTML=`<p class="eyebrow">WEEKLY TEST COMPLETE</p><h2>生成复测</h2><div class="paper-callout"><strong>${wrong.length} 个错词会全部进入复测。</strong><p>另随机加入周测正确词的 20%，并重新混序。</p></div><div class="paper-buttons"><button class="primary-button" data-doc="exam" data-ver="2">下载复测</button><button class="secondary-button" data-action="online-test" data-ver="2">在线复测</button></div>`;return; }
  const gridItems=latest.items.slice(0,200);panel.innerHTML=`<p class="eyebrow">${latest.label||'CURRENT TEST'}</p><h2>在线答题或纸面考试</h2><div class="paper-callout"><strong>${latest.label||'试卷'}共 ${latest.items.length} 题。</strong><p>在线答题与纸面考试放在这里：任选一种完成，再登记错词。</p></div><div class="paper-buttons"><button class="primary-button" data-action="online-test" data-ver="${latest.version}">在线答题</button><button class="secondary-button" data-action="scan-paper" data-ver="${latest.version}">上传勾选卡照片</button><button class="secondary-button" data-doc="exam" data-ver="${latest.version}">下载考试表</button></div><form class="result-box" id="result-form"><h3>快速登记错词</h3><p>可勾选题号、拍照识别或输入题号；图片识别只会自动勾选建议结果。${latest.items.length>200?'当前仅展示前 200 题，其余题号请用批量输入。':''}</p><div class="error-tools"><input id="error-batch" type="text" placeholder="例如：1, 3, 8-10"/><button class="secondary-button" type="button" data-action="apply-error-range">快速填入</button><button class="text-button" type="button" data-action="clear-errors">清空</button></div><div class="error-grid">${gridItems.map(item=>`<label class="error-choice"><input type="checkbox" value="${item.no}" ${wrong.includes(item.no)?'checked':''}/><span>${String(item.no).padStart(2,'0')} · ${esc(item.word.word)}</span></label>`).join('')}</div><button class="primary-button full" type="submit">确认错题并保存</button></form>`;
}
function renderBooks(){q('#wordbook-list').innerHTML=state.wordbooks.map(b=>{const unresolved=b.unresolved_count?'<span class="unresolved-stat">'+b.unresolved_count+' 待补全</span>':'';return `<article class="card book-card" data-action="book-detail" data-book="${b.id}" role="button" tabindex="0"><span class="book-icon"><svg aria-hidden="true"><use href="#i-book"/></svg></span><h2>${esc(b.name)}</h2><p>导入于 ${esc(b.created_at)}</p><div class="dictionary-stats"><span>${b.word_count} 个词条</span><span class="matched-stat">${b.matched_count||0} 已匹配词典</span>${unresolved}</div><div class="card-foot"><button class="text-button" data-action="book-detail" data-book="${b.id}">预览词表与计划</button><button class="text-button" data-action="plan-from-book" data-book="${b.id}">建计划 <svg aria-hidden="true"><use href="#i-arrow"/></svg></button></div></article>`}).join('')||`<div class="empty-state"><h2>还没有词表</h2><p>导入任何格式，只需英文单词；中文释义并非必填。</p><button class="primary-button" data-action="import">导入词表</button></div>`}
function renderPlans(){q('#plans-list').innerHTML=state.plans.map(p=>{const b=book(p),locked=p.week.frozen_word_ids?.length, completed=(p.cycles||[]).filter(c=>c.grade).map(c=>`第${c.number}周期 ${c.grade}`).join(' · ');return `<article class="card plan-card ${p.id===state.active_plan_id?'active-plan':''}"><p class="eyebrow">${p.id===state.active_plan_id?'ACTIVE PLAN':'LEARNING PLAN'}</p><h2>${esc(p.name)}</h2><p>${esc(b?.name||'词表已删除')}</p><span class="tag ${locked?'amber':'teal'}">第 ${p.week.number||1} 周期 · 每周期 ${p.weekly_target||p.week.word_ids.length} 词</span>${completed?`<p class="plan-grade-line">周期评级：${esc(completed)}</p>`:''}<div class="card-foot"><span>${esc(p.start_week)} 开始 · 预计 ${p.estimated_cycles||'—'} 周期</span><button class="text-button" data-action="edit-plan" data-plan="${p.id}">编辑</button>${p.id===state.active_plan_id?'<span>当前计划</span>':`<button class="text-button" data-action="activate" data-plan="${p.id}">切换</button>`}</div></article>`}).join('')||`<div class="empty-state"><h2>还没有计划</h2><p>从已有词表建立一个按周期推进的计划。</p></div>`}
function renderDocuments(){const docs=filter==='all'?state.documents:state.documents.filter(d=>d.type===filter);q('#document-list').innerHTML=docs.map(d=>`<article class="card document-row"><span class="doc-icon">PDF</span><div><h2 title="${esc(d.file_name)}">${esc(d.label)} · rev.${d.revision}</h2><p>${esc(d.created_at)} · ${esc(d.file_name)}</p></div><span class="doc-kind">${d.exam_version?`考试表 ${d.exam_version}`:'本周材料'}</span><div class="doc-actions"><button class="icon-button" aria-label="预览 ${esc(d.label)}" data-action="preview" data-url="${d.preview_url}"><svg aria-hidden="true"><use href="#i-eye"/></svg></button><button class="secondary-button" data-action="download" data-url="${d.download_url}" data-name="${esc(d.file_name)}"><svg aria-hidden="true"><use href="#i-download"/></svg>下载</button></div></article>`).join('')||`<div class="empty-state"><svg aria-hidden="true"><use href="#i-file"/></svg><h2>文档中心还是空的</h2><p>从背诵表或考试表点击“生成并下载”，第一份 PDF 会自动保存到这里。</p></div>`}

const checkList=(list,selected=[])=>list.map(w=>`<label class="check-item"><input type="checkbox" value="${w.id}" ${selected.includes(w.id)?'checked':''}/><b>${esc(w.word)}</b><span>${esc(w.meaning)}</span></label>`).join('');
function open(id){q(id).showModal()}
function clearImport(){importContent='';importPreview=[];q('#import-preview').classList.add('hidden');q('#import-error').classList.add('hidden');q('#import-error').textContent='';q('#preview-import').classList.remove('hidden');q('#preview-import').disabled=false;q('#preview-import').textContent='识别并预览';q('#confirm-import').classList.add('hidden');q('#confirm-import').disabled=false;}
function openImport(){clearImport();if(!q('#import-shuffle')){const label=document.createElement('label');label.className='shuffle-choice';label.innerHTML='<input id="import-shuffle" type="checkbox"/> <span>将本词表乱序导入</span><small>只改变学习与出题的初始顺序，词表内容不变。</small>';q('#import-name').closest('label').after(label)}q('#import-shuffle').checked=false;q('#file-input').value='';q('#file-label').textContent='选择单词本文件';q('#import-name').value='';open('#import-dialog')}
function planDialog(bookId){if(!state.wordbooks.length){notice('请先导入一个词表。');return}q('#new-plan-book').innerHTML=state.wordbooks.map(b=>`<option value="${b.id}" ${b.id===bookId?'selected':''}>${esc(b.name)} · ${b.word_count} 词</option>`).join('');q('#new-plan-date').value=new Date().toISOString().slice(0,10); newPlanWords();open('#plan-dialog')}
function newPlanWords(){const b=state.wordbooks.find(x=>x.id===q('#new-plan-book').value), target=Math.max(1,Number(q('#new-plan-target').value)||30),old=Math.max(1,Math.round(target*.1)),cycles=b?b.word_count<=target?1:1+Math.ceil((b.word_count-target)/Math.max(1,target-old)):0;q('#plan-estimate').textContent=b?`预计约 ${cycles} 个周期完成；从第 2 周期起，每周期约 ${old} 个旧词复习。`:''}
function weekDialog(){const p=plan();if(!p)return;q('#words-dialog-help').textContent='本周期由计划自动排入；从第二周期起，约 10% 为此前学过的词。';q('#active-plan-words').innerHTML=checkList(words(p),p.week.word_ids);qa('#active-plan-words input').forEach(x=>x.disabled=true);const save=q('[data-action="save-week-words"]');save.hidden=true;open('#words-dialog')}
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name||'';document.body.append(a);a.click();a.remove()}
async function generate(type,version){const p=plan();if(!p)return notice('请先建立学习计划。');try{const {document:doc}=await api('/api/documents/generate',{method:'POST',body:JSON.stringify({plan_id:p.id,type,exam_version:version})});await refresh();download(doc.download_url,doc.file_name);notice(`已保存到文档中心，正在下载 ${doc.label}。`)}catch(e){notice(e.message)}}
function showImportError(message){const el=q('#import-error');el.textContent=message;el.classList.remove('hidden');el.focus()}
function renderImportPreview(summary){q('#preview-count').textContent=`${importPreview.length} 词`;q('#preview-summary').textContent=`识别 ${summary.candidate_count} 词 · 词典匹配 ${summary.matched_count} · 待补全 ${summary.unresolved_count}${summary.duplicate_count?` · 去重 ${summary.duplicate_count}`:''}`;q('#preview-list').innerHTML=importPreview.map(item=>`<label class="preview-item"><input type="checkbox" value="${esc(item.normalized_word)}" checked/><div class="preview-word"><b>${esc(item.word)}</b><small>${esc(item.source)}</small></div><div class="preview-meaning">${item.meaning?esc(item.meaning):'尚未收录，可导入后补全'}</div><span class="match-chip ${item.match_status}">${item.match_status==='matched'?'已匹配':'待补全'}</span></label>`).join('');q('#import-preview').classList.remove('hidden');q('#preview-import').classList.add('hidden');q('#confirm-import').classList.remove('hidden');q('#confirm-import').textContent=`确认导入 ${importPreview.length} 词`}
async function previewBook(){const f=q('#file-input').files[0];if(!f){showImportError('请选择 TXT、JSON、CSV、XLS 或 XLSX 单词本。');return}const b=q('#preview-import');b.disabled=true;b.textContent='正在识别…';q('#import-error').classList.add('hidden');try{importContent=await new Promise((yes,no)=>{const r=new FileReader();r.onload=()=>yes(r.result);r.onerror=no;r.readAsDataURL(f)});const r=await api('/api/import/preview',{method:'POST',body:JSON.stringify({filename:f.name,content:importContent})});importPreview=r.preview;renderImportPreview(r.summary)}catch(e){showImportError(e.message)}finally{b.disabled=false;b.textContent='识别并预览'}}
async function importBook(){const f=q('#file-input').files[0], selected=qa('#preview-list input:checked').map(x=>x.value);if(!f||!importContent)return previewBook();if(!selected.length){showImportError('请至少勾选 1 个词条再导入。');return}const b=q('#confirm-import');b.disabled=true;b.textContent='正在保存…';try{const r=await api('/api/import/confirm',{method:'POST',body:JSON.stringify({filename:f.name,name:q('#import-name').value.trim(),content:importContent,selected_words:selected,shuffle:q('#import-shuffle')?.checked})});q('#import-dialog').close();await refresh();view('wordbooks');notice(`已导入「${r.wordbook.name}」：${r.wordbook.word_count} 个词，其中 ${r.wordbook.matched_count} 个已匹配词典。`)}catch(e){showImportError(e.message)}finally{b.disabled=false;b.textContent='确认导入'}}
async function createPlan(){const target=Number(q('#new-plan-target').value)||0;try{await api('/api/plans',{method:'POST',body:JSON.stringify({name:q('#new-plan-name').value.trim(),wordbook_id:q('#new-plan-book').value,start_week:q('#new-plan-date').value,weekly_target:target})});q('#plan-dialog').close();await refresh();view('dashboard');notice(`周期计划已建立：每周期 ${target} 词。`)}catch(e){notice(e.message)}}
async function saveWords(){const p=plan(),ids=qa('#active-plan-words input:checked').map(x=>x.value);try{await api(`/api/plans/${p.id}/words`,{method:'POST',body:JSON.stringify({word_ids:ids})});q('#words-dialog').close();await refresh();notice(`本周词条已更新：${ids.length} 个。`)}catch(e){notice(e.message)}}
async function saveResult(){const p=plan(),latest=papers().at(-1),ids=[...new Set([...qa('#result-form input:checked').map(x=>Number(x.value)),...batchWrongNumbers])];try{await api(`/api/exams/${latest.version}/result`,{method:'POST',body:JSON.stringify({plan_id:p.id,wrong_numbers:ids})});await refresh();notice(`考试表 ${latest.version} 的 ${ids.length} 个错词已保存。`)}catch(e){notice(e.message)}}

let onlineQuestion=null,onlineIndex=0,onlineTotal=0,onlineVersion=1,onlineWrong=[];
function bookDialog(bookId){const b=state.wordbooks.find(x=>x.id===bookId);if(!b)return;q('#book-detail-title').textContent=b.name;q('#book-detail-meta').textContent=`${b.word_count} 词 · ${b.matched_count||0} 词已匹配内置词典`;q('#book-edit-name').value=b.name;q('#book-add-words').value='';q('#book-detail-plans').innerHTML=state.plans.filter(p=>p.wordbook_id===b.id).map(p=>`<div class="book-plan-row"><b>${esc(p.name)}</b><span>第 ${p.week?.number||1} 周期 / ${p.estimated_cycles||'—'} · ${p.week?.grade||'进行中'}</span></div>`).join('')||'<p class="preview-help">这个词表尚未创建学习计划。</p>';const preview=b.words.slice(0,200);q('#book-word-help').textContent=b.words.length>200?`为保证页面流畅，当前显示前 200 / ${b.words.length} 个词；可勾选后删除。`: '勾选词条后可删除；正在被计划使用的词条会受到保护。';q('#book-detail-words').innerHTML=checkList(preview,[]);q('#book-dialog').dataset.book=b.id;open('#book-dialog')}
async function saveBook(){const id=q('#book-dialog').dataset.book;try{await api(`/api/wordbooks/${id}`,{method:'POST',body:JSON.stringify({name:q('#book-edit-name').value.trim(),add_words:q('#book-add-words').value})});await refresh();bookDialog(id);notice('词表已保存。')}catch(e){notice(e.message)}}
async function deleteSelectedWords(){const id=q('#book-dialog').dataset.book,ids=qa('#book-detail-words input:checked').map(x=>x.value);if(!ids.length)return notice('请先勾选要删除的词。');if(!confirm(`确定删除选中的 ${ids.length} 个词吗？`))return;try{await api(`/api/wordbooks/${id}/delete-words`,{method:'POST',body:JSON.stringify({word_ids:ids})});await refresh();bookDialog(id);notice('已删除选中词。')}catch(e){notice(e.message)}}
async function deleteBook(){const id=q('#book-dialog').dataset.book;if(!confirm('确定删除整个词表吗？关联计划存在时会被保护，需先删除计划。'))return;try{await api(`/api/wordbooks/${id}/delete`,{method:'POST',body:'{}'});q('#book-dialog').close();await refresh();notice('词表已删除。')}catch(e){notice(e.message)}}
function planEditDialog(id){const p=state.plans.find(x=>x.id===id);if(!p)return;q('#edit-plan-id').value=id;q('#edit-plan-name').value=p.name;q('#edit-plan-target').value=p.weekly_target||p.week.word_ids.length;q('#edit-plan-date').value=p.start_week;open('#plan-edit-dialog')}
async function savePlan(){const id=q('#edit-plan-id').value;try{await api(`/api/plans/${id}`,{method:'POST',body:JSON.stringify({name:q('#edit-plan-name').value.trim(),weekly_target:Number(q('#edit-plan-target').value),start_week:q('#edit-plan-date').value})});q('#plan-edit-dialog').close();await refresh();notice('计划已保存；新的每周期数量将在后续周期生效。')}catch(e){notice(e.message)}}
async function deletePlan(){const id=q('#edit-plan-id').value;if(!confirm('确定删除此计划吗？已生成的 PDF 会继续保留在文档中心。'))return;try{await api(`/api/plans/${id}/delete`,{method:'POST',body:'{}'});q('#plan-edit-dialog').close();await refresh();notice('计划已删除。')}catch(e){notice(e.message)}}
async function fetchOnlineQuestion(){const p=plan(),r=await api(`/api/exams/${onlineVersion}/online?plan_id=${encodeURIComponent(p.id)}&index=${onlineIndex}`);onlineQuestion=r.question;onlineTotal=r.total;q('#online-kicker').textContent=r.paper.label+' · ONLINE';renderOnlineQuestion()}
async function onlineTest(version){const p=plan();if(!p)return;try{onlineVersion=version;onlineIndex=0;onlineWrong=[];q('#online-word').textContent='正在准备题目…';q('#online-options').innerHTML='';open('#online-dialog');await fetchOnlineQuestion();await refresh()}catch(e){q('#online-dialog').close();notice(`在线测试未能启动：${e.message}`)}}
function renderOnlineQuestion(){const item=onlineQuestion;if(!item)return;q('#online-word').textContent=item.word;q('#online-count').textContent=`第 ${onlineIndex+1} / ${onlineTotal} 题`;q('#online-options').innerHTML=item.choices.map(choice=>`<button class="online-option" data-choice="${esc(choice)}">${esc(choice)}</button>`).join('');q('#online-feedback').classList.add('hidden');q('#online-next').classList.add('hidden')}
function answerOnline(choice){const item=onlineQuestion,correct=choice===item.answer;if(!correct)onlineWrong.push(item.no);qa('.online-option').forEach(button=>{button.disabled=true;button.classList.toggle('correct',button.dataset.choice===item.answer);button.classList.toggle('wrong',button.dataset.choice===choice&&!correct)});q('#online-feedback').innerHTML=`<strong>${correct?'回答正确':'需要复习'}</strong><p>${esc(item.word)} · ${esc(item.phonetic)} ${esc(item.part_of_speech)}</p><p>${esc(item.meaning)}</p><ul>${item.examples.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;q('#online-feedback').classList.remove('hidden');q('#online-next').classList.remove('hidden');q('#online-next').textContent=onlineIndex===onlineTotal-1?'提交本次结果':'下一题'}
async function nextOnline(){if(onlineIndex<onlineTotal-1){onlineIndex++;try{q('#online-next').disabled=true;q('#online-next').textContent='加载下一题…';await fetchOnlineQuestion()}catch(e){notice(`下一题加载失败：${e.message}`)}return}const p=plan();try{await api(`/api/exams/${onlineVersion}/result`,{method:'POST',body:JSON.stringify({plan_id:p.id,wrong_numbers:onlineWrong})});q('#online-dialog').close();await refresh();notice(`已保存 ${onlineWrong.length} 个错词。`)}catch(e){notice(e.message)}}
async function scanPaper(file){const p=plan(),latest=papers(p).at(-1);if(!file||!latest)return;try{notice('正在核验答题卡页面并识别勾选…');const image=await new Promise((yes,no)=>{const r=new FileReader();r.onload=()=>yes(r.result);r.onerror=no;r.readAsDataURL(file)});const r=await api(`/api/exams/${latest.version}/scan`,{method:'POST',body:JSON.stringify({plan_id:p.id,image})});const selected=new Set(r.suggested_wrong_numbers);qa('#result-form input').forEach(input=>input.checked=selected.has(Number(input.value)));notice(r.message)}catch(e){notice(e.message)}finally{q('#scan-input').value=''}}
function applyErrorRange(){const max=papers().at(-1)?.items.length||0,raw=q('#error-batch')?.value.trim()||'',marked=new Set();for(const token of raw.split(/[,，\s]+/)){if(!token)continue;const pair=token.split('-').map(x=>Number(x));if(pair.length===1&&Number.isInteger(pair[0]))marked.add(pair[0]);if(pair.length===2&&Number.isInteger(pair[0])&&Number.isInteger(pair[1]))for(let i=Math.min(...pair);i<=Math.max(...pair);i++)marked.add(i)}batchWrongNumbers=new Set([...marked].filter(x=>x>=1&&x<=max));qa('#result-form input[type="checkbox"]').forEach(input=>input.checked=batchWrongNumbers.has(Number(input.value)));notice(`已勾选 ${batchWrongNumbers.size} 题，请核对后保存。`)}

document.addEventListener('click',async e=>{const nav=e.target.closest('[data-view]');if(nav){view(nav.dataset.view);return}const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;qa('.filter').forEach(x=>x.classList.toggle('active',x===f));renderDocuments();return}const choice=e.target.closest('[data-choice]');if(choice){answerOnline(choice.dataset.choice);return}const doc=e.target.closest('[data-doc]');if(doc){await generate(doc.dataset.doc,Number(doc.dataset.ver));return}const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='import')openImport();if(a==='new-plan')planDialog();if(a==='plan-from-book')planDialog(b.dataset.book);if(a==='book-detail')bookDialog(b.dataset.book);if(a==='save-book')await saveBook();if(a==='delete-selected-words')await deleteSelectedWords();if(a==='delete-book')await deleteBook();if(a==='edit-plan')planEditDialog(b.dataset.plan);if(a==='save-plan')await savePlan();if(a==='delete-plan')await deletePlan();if(a==='manage-words')weekDialog();if(a==='preview-import')await previewBook();if(a==='confirm-import')await importBook();if(a==='confirm-plan')await createPlan();if(a==='save-week-words')await saveWords();if(a==='generate-study')await generate('study');if(a==='exam-one')await generate('exam',1);if(a==='online-test')await onlineTest(Number(b.dataset.ver));if(a==='online-next')await nextOnline();if(a==='scan-paper'){q('#scan-input').click()}if(a==='apply-error-range')applyErrorRange();if(a==='clear-errors'){qa('#result-form input[type="checkbox"]').forEach(input=>input.checked=false);q('#error-batch').value=''}if(a==='open-docs')view('documents');if(a==='refresh-docs'){await refresh();notice('文档中心已刷新。')}if(a==='preview')window.open(b.dataset.url,'_blank','noopener');if(a==='download'){download(b.dataset.url,b.dataset.name);notice('正在下载已保存的文档。')}if(a==='activate'){try{await api('/api/active-plan',{method:'POST',body:JSON.stringify({plan_id:b.dataset.plan})});await refresh();view('dashboard');notice('已切换到该学习计划。')}catch(err){notice(err.message)}}if(a==='mobile-menu')notice('小屏幕上请使用页面内按钮；完整导航在桌面端侧栏。')});
document.addEventListener('submit',e=>{if(e.target.id==='result-form'){e.preventDefault();saveResult()}});
document.addEventListener('click',e=>{if(e.target.closest('[data-action="clear-errors"]'))batchWrongNumbers.clear()});
document.addEventListener('keydown',e=>{const card=e.target.closest?.('.book-card[data-book]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();bookDialog(card.dataset.book)}});
q('#file-input').addEventListener('change',()=>{const f=q('#file-input').files[0];q('#file-label').textContent=f?f.name:'选择单词本文件';importContent='';importPreview=[];q('#import-preview').classList.add('hidden');q('#import-error').classList.add('hidden');q('#preview-import').classList.remove('hidden');q('#confirm-import').classList.add('hidden')});q('#scan-input').addEventListener('change',()=>scanPaper(q('#scan-input').files[0]));q('#new-plan-book').addEventListener('change',newPlanWords);q('#new-plan-target').addEventListener('input',newPlanWords);
refresh().catch(e=>{q('#dashboard').innerHTML=`<div class="empty-state"><h2>无法连接本地服务</h2><p>${esc(e.message)}。请运行 server.py 后刷新页面。</p></div>`});
